import { type MealPlan } from './ai';

export function generateICSFile(mealPlan: MealPlan, userName: string): string {
  const now = new Date();
  const startDate = new Date(now);
  startDate.setHours(0, 0, 0, 0);

  let icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//NutriNudge//Meal Plan//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:${userName}'s Meal Plan
X-WR-TIMEZONE:UTC
X-WR-CALDESC:Personalized meal plan generated by NutriNudge\n`;

  const mealTimes = {
    breakfast: { hour: 8, minute: 0 },
    lunch: { hour: 13, minute: 0 },
    dinner: { hour: 19, minute: 0 },
    snack: { hour: 16, minute: 0 },
    snacks: { hour: 16, minute: 0 }
  };

  mealPlan.days.forEach((day, dayIndex) => {
    const currentDate = new Date(startDate);
    currentDate.setDate(startDate.getDate() + dayIndex);

    day.meals.forEach(meal => {
      const mealType = meal.type.toLowerCase();
      const timeConfig = mealTimes[mealType as keyof typeof mealTimes] || { hour: 12, minute: 0 };
      
      const eventStart = new Date(currentDate);
      eventStart.setHours(timeConfig.hour, timeConfig.minute, 0, 0);
      
      const eventEnd = new Date(eventStart);
      eventEnd.setMinutes(eventEnd.getMinutes() + 30);

      const uid = `${dayIndex}-${mealType}-${Date.now()}@nutrinudge.app`;
      const summary = `${capitalizeFirstLetter(mealType)}: ${meal.name}`;
      const description = `Portions: ${meal.portions}\\nCalories: ${meal.calories} kcal\\nProtein: ${meal.macros.protein_g}g\\nCarbs: ${meal.macros.carbs_g}g\\nFats: ${meal.macros.fat_g}g`;

      icsContent += `BEGIN:VEVENT
UID:${uid}
DTSTAMP:${formatICSDate(now)}
DTSTART:${formatICSDate(eventStart)}
DTEND:${formatICSDate(eventEnd)}
SUMMARY:${summary}
DESCRIPTION:${description}
CATEGORIES:MEAL,${meal.type.toUpperCase()}
STATUS:CONFIRMED
END:VEVENT\n`;
    });
  });

  icsContent += 'END:VCALENDAR';
  return icsContent;
}

function formatICSDate(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  const seconds = String(date.getSeconds()).padStart(2, '0');
  
  return `${year}${month}${day}T${hours}${minutes}${seconds}Z`;
}

function capitalizeFirstLetter(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export function downloadICSFile(icsContent: string, fileName: string): void {
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
