import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface MealItem {
  name: string;
  portion: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
}

interface DayPlan {
  breakfast: MealItem[];
  lunch: MealItem[];
  dinner: MealItem[];
  snacks: MealItem[];
}

interface UserData {
  name: string;
  goal: string;
}

export function generateMealPlanPDF(
  userData: UserData,
  dailyCalories: number,
  macros: { protein: number; carbs: number; fats: number },
  mealPlan: DayPlan
) {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(24);
  doc.setTextColor(34, 197, 94); // Primary green color
  doc.text('NutriNudge Meal Plan', 105, 20, { align: 'center' });
  
  // User Info
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Personalized Plan for: ${userData.name}`, 20, 35);
  doc.text(`Goal: ${formatGoal(userData.goal)}`, 20, 42);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 49);
  
  // Daily Targets
  doc.setFontSize(14);
  doc.setTextColor(34, 197, 94);
  doc.text('Daily Nutritional Targets', 20, 60);
  
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Calories: ${dailyCalories} kcal`, 20, 68);
  doc.text(`Protein: ${macros.protein}g`, 20, 75);
  doc.text(`Carbs: ${macros.carbs}g`, 20, 82);
  doc.text(`Fats: ${macros.fats}g`, 20, 89);
  
  // Meal Plan Section
  let yPosition = 100;
  
  const mealTypes = ['breakfast', 'lunch', 'dinner', 'snacks'] as const;
  
  mealTypes.forEach((mealType) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    
    doc.setFontSize(13);
    doc.setTextColor(34, 197, 94);
    doc.text(mealType.charAt(0).toUpperCase() + mealType.slice(1), 20, yPosition);
    yPosition += 7;
    
    const meals = mealPlan[mealType];
    const tableData = meals.map(meal => [
      meal.name,
      meal.portion,
      meal.calories,
      meal.protein,
      meal.carbs,
      meal.fats
    ]);
    
    autoTable(doc, {
      startY: yPosition,
      head: [['Food Item', 'Portion', 'Cal', 'P(g)', 'C(g)', 'F(g)']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [34, 197, 94] },
      margin: { left: 20, right: 20 },
      styles: { fontSize: 9 },
    });
    
    yPosition = (doc as any).lastAutoTable.finalY + 10;
  });
  
  // Add new page for tips
  doc.addPage();
  
  // Smart Tips
  doc.setFontSize(14);
  doc.setTextColor(34, 197, 94);
  doc.text('Smart Tips', 20, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  const tips = [
    '• Stay hydrated with at least 2-3 liters of water daily',
    '• Add 1 tbsp flaxseed to your oats for better omega-3 intake',
    '• Consider meal prepping on Sundays to stay on track',
    '• Track your progress weekly and adjust portions as needed',
    '• Get adequate sleep (7-9 hours) for optimal results',
    '• Listen to your body and adjust portions if needed'
  ];
  
  let tipY = 30;
  tips.forEach(tip => {
    doc.text(tip, 20, tipY);
    tipY += 7;
  });
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by NutriNudge - Your AI Nutrition Partner', 105, 280, { align: 'center' });
  
  // Save the PDF
  doc.save(`NutriNudge_Meal_Plan_${userData.name.replace(/\s+/g, '_')}.pdf`);
}

function formatGoal(goal: string): string {
  const goalMap: Record<string, string> = {
    'weight-loss': 'Weight Loss',
    'muscle-gain': 'Muscle Gain',
    'maintenance': 'Maintenance',
    'diabetes': 'Manage Diabetes',
    'pcos': 'Manage PCOS',
    'clean-eating': 'Clean Eating'
  };
  return goalMap[goal] || goal;
}
